version: '3.8'

services:
  postgres:
    container_name: virtus_vox_postgres
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  cache:
    container_name: virtus_vox_redis
    image: redis
    ports: 
      - "6379:6379"